# Generated by Django 4.1.2 on 2022-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_rename_articles_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
